[build]
  base = "kaypeter.com"
  command = "hugo --gc --themesDir ../.. -b $URL"
  publish = "kaypeter.com/public"

[build.environment]
  HUGO_THEME = "repo"

[context.deploy-preview]
  command = "hugo --gc --themesDir ../.. -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --themesDir ../.. -b $DEPLOY_PRIME_URL"
